; PlatformIO Project Configuration File
;
;   Build options: build flag s, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; env - 한 보드(한 MCU)를 빌드하고 업로드하기 위한 세트(=환경)
;(환경 하나에 하나의 MCU가 들어감)
; PlatformIO의 핵심 개념 - "환경(env) 기준"으로 동작하기 때문에 
; 즉, ❌ src/esp32cam/main.cpp를 선택해서 업로드 ❌/ ✅ env:esp32cam을 선택해서 업로드 ✅
; monitor_rts = 0 / monitor_dtr = 0 => Monitor가 RTS/DTR을 아예 건드리지 마라

;=============================
; ATmega328p-au 환경
;=============================
[env:uno_usbasp]
platform = atmelavr
board = uno
framework = arduino
upload_protocol = usbasp
upload_flags = -e
board_build.f_cpu = 16000000L
monitor_speed = 115200
build_flags =
  -DSERIAL_TX_BUFFER_SIZE=16
  -DTWI_BUFFER_LENGTH=16
  -Wl,--relax

lib_deps =
  bogde/HX711@^0.7.5
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
  https://github.com/sstaub/Ethernet3.git#1.5.3

; ★ 핵심: atmega 폴더만 컴파일
build_src_filter =
  -<*>
  +<atmega/>

; ;=============================
; ; ESP32-CAM 환경
; ;=============================
; [env:esp32cam]
; platform = espressif32
; board = esp32cam
; framework = arduino
; upload_protocol = esptool
; upload_speed = 921600
; monitor_speed = 115200
; monitor_rts = 0
; monitor_dtr = 0 
; upload_port = COM9
; monitor_port = COM9

; ; ★ PSRAM 활성화 (VGA 해상도 사용 시 필수)
; build_flags = -DBOARD_HAS_PSRAM

; ; ★ 핵심: esp32cam 폴더만 컴파일
; build_src_filter =
;   -<*>
;   +<esp32cam/>

